# Generated by Django 5.2.8 on 2025-11-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
