# Generated by Django 5.2.8 on 2025-11-26 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5)),
                ('number', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('REGULAR', 'Regular Seat'), ('PREMIUM', 'Premium Seat'), ('VIP', 'VIP Seat')], default='REGULAR', max_length=10)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.screen')),
            ],
            options={
                'ordering': ['row', 'number'],
                'unique_together': {('row', 'number', 'screen')},
            },
        ),
    ]
