# Generated by Django 5.2.8 on 2025-11-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Ticket price in USD', max_digits=6),
        ),
    ]
